//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project0_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessAccount
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public bool Active { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
